export const streamers = [{
      "name": "Nebe Gameplays",
      "channel": "NebeGameplays",
      "group": "6",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "Nebe#3352072"
    },
    {
      "name": "eduredon",
      "channel": "eduredon",
      "group": "6",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "xMadeInGulag",
      "channel": "xmadeingulag",
      "group": "3",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Marduk",
      "channel": "marduky",
      "group": "5",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Gral Rodriguez",
      "channel": "Gral_Rodriguez",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "zMaangoo",
      "channel": "zMaangoo",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "elpetycabron",
      "channel": "elpetycabron",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "LittleRbt69",
      "channel": "littlerbt69",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "makktub27",
      "channel": "makktub27",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "MerkOne",
      "channel": "merkonei",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Tatoel10",
      "channel": "Tatoel10",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "XL0VECR4FT_",
      "channel": "XL0VECR4FT_",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Rubenn122",
      "channel": "Rubenn122",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "TheSicu11",
      "channel": "thesicu11",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "yizoon31",
      "channel": "yizoon31",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "fcoracing21",
      "channel": "fcoracing21",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Joako85",
      "channel": "Joako85",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Zionsnake",
      "channel": "zionsnake",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Karlytox81",
      "channel": "Karlytox81",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "ToxicMonkeysLive",
      "channel": "toxicmonkeyslive",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Sasgdl_",
      "channel": "sasgdl_",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "adrithekid",
      "channel": "adrithekid",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "charlie_sos",
      "channel": "charlie_sos",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "kingz_gamiing",
      "channel": "kingz_gamiing",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Diommi23_",
      "channel": "Diommi23_",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "santiaakou",
      "channel": "santiaakou",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "elmaletas60",
      "channel": "elmaletas60",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "ElMacDG",
      "channel": "el_macdg",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Shadek",
      "channel": "shadekg",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "pikarin_tv",
      "channel": "pikarin_tv",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "themasterofgame0",
      "channel": "themasterofgame0",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "nannoreal",
      "channel": "nannoreal",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "manolomartinezgiraldo",
      "channel": "manolomartinezgiraldo",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "naachoossj",
      "channel": "naachoossj",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "budha94_",
      "channel": "budha94_",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Weedatv",
      "channel": "weedatv",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "josecor_swos",
      "channel": "josecor_swos",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "puravida20268",
      "channel": "puravida20268",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "pastricia",
      "channel": "pastricia",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Nano_eldatv",
      "channel": "nano_eldatv",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "theepunishertv",
      "channel": "theepunishertv",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "xelcharruax",
      "channel": "xelcharruax",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "JotaSniper92",
      "channel": "JotaSniper92",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Kako2351",
      "channel": "Kako2351",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "oscurodani",
      "channel": "oscurodani",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Cristian27_eldatv",
      "channel": "Cristian27_eldatv",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "babayagalp",
      "channel": "babayagalp",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "mrlolgfx",
      "channel": "mrlolgfx",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "brossgamerx",
      "channel": "brossgamerx",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "cristian_granada",
      "channel": "cristian_granada",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "joako85",
      "channel": "joako85",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Preison",
      "channel": "prason7",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "spectrum2312",
      "channel": "spectrum2312",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "new_itsjona02",
      "channel": "new_itsjona02",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Kolombo1988",
      "channel": "kolombo1988",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "andrewrodriguew",
      "channel": "andrewrodriguew",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Gabo_Conejo",
      "channel": "gabo_conejo23",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Simbiotik85",
      "channel": "simbiotik85",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Jonels05",
      "channel": "jonels05",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Biza13",
      "channel": "biza_13",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Tristanchuc_",
      "channel": "tristanchuc_",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Mxniiako",
      "channel": "mxniiako",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "CharliUchiha",
      "channel": "charliuchiha",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Krakencosmico",
      "channel": "krakencosmico",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Nesthor96",
      "channel": "nes_thor96",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "secolomeli96",
      "channel": "secolomeli96",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Najet96",
      "channel": "xnajettw",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Bigthejoker",
      "channel": "bigthejokeryt",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Carlicox135",
      "channel": "carlicox135",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Kamikazze_Team",
      "channel": "Kamikazze_Team",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Xexu",
      "channel": "xexu_watchmen",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "jimmy07899",
      "channel": "jimmy07899",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "pepo4",
      "channel": "pepo4",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "aspim",
      "channel": "aspim",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "greenmonkeey1",
      "channel": "greenmonkeey1",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "MonchoChavea15",
      "channel": "monchochavea15",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Motelwzn",
      "channel": "motelwzn",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "ggi779",
      "channel": "ggi779",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Kev_cr10",
      "channel": "kev_cr10",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "nanattosback",
      "channel": "nanattosback",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "ElYayoGamer",
      "channel": "el_yayo_gamer",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Yorcher2020",
      "channel": "yorcher2020",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Samuelxere",
      "channel": "samuelxere",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Majete_pk",
      "channel": "majete_pk",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "twistedbull02",
      "channel": "twistedbull02",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Charliuchiha27",
      "channel": "Charliuchiha27",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "andreu_s_r97",
      "channel": "andreu_s_r97",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "ElTakuache_",
      "channel": "eltakuache_",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Kurita8",
      "channel": "kurita8",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "elcochilocotv",
      "channel": "elcochilocotv",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "pichichigamer0",
      "channel": "pichichigamer0",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "babyionya",
      "channel": "babyionya",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "jotatubala",
      "channel": "jotatubala",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Jcalzon10",
      "channel": "jcalzon10",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Pollojeri",
      "channel": "Pollojeri",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "XxSTARxX|xdarkoff",
      "channel": "xdarkoff",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "piccoleador",
      "channel": "piccoleador",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "encuarentenaoficial",
      "channel": "encuarentenaoficial",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Paloteli",
      "channel": "paloteli",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "victikogonzalez",
      "channel": "victikogonzalez",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "m11medina",
      "channel": "m11medina",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "morferuss",
      "channel": "morferuss",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "jimmy07899",
      "channel": "jimmy07899",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "3892_jos",
      "channel": "3892_jos",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "AMartinex",
      "channel": "AMartinex",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "byisaac1",
      "channel": "byisaac1",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "hitman_35226",
      "channel": "hitman_35226",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Stylee_",
      "channel": "stylee_",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Sekerflay",
      "channel": "sekerflay",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "CrazyFlexxYT",
      "channel": "crazyflexxyt",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Pneonfire",
      "channel": "Pneonfire",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "vcm97",
      "channel": "vcm97",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Morbear",
      "channel": "morbear_",
      "group": "6",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "andrewrodriguewuy",
      "channel": "andrewrodriguewuy",
      "group": "6",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "nowey2595",
      "channel": "nowey2595",
      "group": "6",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "budigamergirl",
      "channel": "budigamergirl",
      "group": "6",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "ByAlann",
      "channel": "ByAlann",
      "group": "6",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "La_crispa89",
      "channel": "La_crispa89",
      "group": "6",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "xxylogicxx",
      "channel": "xxylogicxx",
      "group": "6",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "blascovision",
      "channel": "blascovision",
      "group": "6",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "manuhe1994",
      "channel": "manuhe1994",
      "group": "6",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Botafuumeir0",
      "channel": "Botafuumeir0",
      "group": "6",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "LotusBlack",
      "channel": "emperorinriver",
      "group": "6",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "FakeYuki",
      "channel": "fakeyuukiuwu",
      "group": "6",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "CorsarioGBK",
      "channel": "corsariogbk",
      "group": "6",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Sheygam3r",
      "channel": "sheyprz",
      "group": "6",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "DocKiller",
      "channel": "dockilleer",
      "group": "6",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "theforantu",
      "channel": "theforantu",
      "group": "2",
      "raid": "1",
      "admin": "1",
      "showstream": "1",
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    }
  ]