export const streamers = [{
      "name": "Nebe Gameplays",
      "channel": "NebeGameplays",
      "group": "6",
      "raid": "0",
      "admin": "1",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "Nebe#3352072"
    },
    {
      "name": "eduredon",
      "channel": "eduredon",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "xMadeInGulag",
      "channel": "xmadeingulag",
      "group": "3",
      "raid": "0",
      "admin": "1",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "MaDeInGuLaG#9184907"
    },
    {
      "name": "Marduk",
      "channel": "marduky",
      "group": "5",
      "raid": "0",
      "admin": "1",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "Marduky#2408056"
    },
    {
      "name": "Gral Rodriguez",
      "channel": "Gral_Rodriguez",
      "group": "2",
      "raid": "0",
      "admin": "1",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "zMaangoo",
      "channel": "zmaangoo",
      "group": "2",
      "raid": "0",
      "admin": "1",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "Twitch zMaangooツ#1658907"
    },
    {
      "name": "ElPetyCabron",
      "channel": "elpetycabron",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "ELPETYCABRON#3798789"
    },
    {
      "name": "LittleRbt69",
      "channel": "littlerbt69",
      "group": "2",
      "raid": "0",
      "admin": "1",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "twch Littlerbt69#9031308"
    },
    {
      "name": "TheYOKO",
      "channel": "theyoko_yt",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "twch Littlerbt69#9031308"
    },
    {
      "name": "makktub27",
      "channel": "makktub27",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "MerkOneI",
      "channel": "merkonei",
      "group": "2",
      "raid": "0",
      "admin": "1",
      "showstream": false,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Tatoel10",
      "channel": "Tatoel10",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "vpPedrosaa",
      "channel": "vppedrosaa",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "Vppedrosa#8504418"
    },
    {
      "name": "Adespresa",
      "channel": "adespresa",
      "group": "3",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "MaDeInGuLaG#9184907"
    },
    {
      "name": "JoaquinFari",
      "channel": "joaquinfari",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "OskarMaao",
      "channel": "oskarmaao",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Neodgc",
      "channel": "Neodgc",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "NanoSpeedSoft",
      "channel": "nanospeedsoft",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "xL0VECR4FT_",
      "channel": "xlovecraft_",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "xL0V3CR4FT#7932294"
    },
    {
      "name": "Rubenn122",
      "channel": "Rubenn122",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "TheSicu11",
      "channel": "thesicu11",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "yizoon31",
      "channel": "yizoon31",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "fcoracing21",
      "channel": "fcoracing21",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Joako85",
      "channel": "joako85",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Zionsnake",
      "channel": "zionsnake",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": false,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Karlytox81",
      "channel": "Karlytox81",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "Karlytox-81#9956418"
    },
    {
      "name": "ToxicMonkeysLive",
      "channel": "toxicmonkeyslive",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Sasgdl_",
      "channel": "sasgdl_",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "sasgdl#5653146"
    },
    {
      "name": "AdriTheKid",
      "channel": "adrithekid",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "NicoBarbaLive",
      "channel": "nicobarbalive",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "GiusePPeBF",
      "channel": "giuseppebf",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Gumcuba",
      "channel": "Gumcuba",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "JuanFaraone",
      "channel": "juanfaraone",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "vmozzi07",
      "channel": "vmozzi07",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Kisco19",
      "channel": "kisco19",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "TwitchLucer",
      "channel": "twitchlucer",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "christellodgames",
      "channel": "christellodgames",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "BigTatuu",
      "channel": "bigtatuu",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "charlie_sos",
      "channel": "charlie_sos",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "kingz_gamiing",
      "channel": "kingz_gamiing",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Diommi23_",
      "channel": "Diommi23_",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "santiaakou",
      "channel": "santiaakou",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "elmaletas60",
      "channel": "elmaletas60",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "El_MacDG",
      "channel": "el_macdg",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Shadek",
      "channel": "shadekg",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Pikarin_TV",
      "channel": "pikarin_tv",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Maariiaacv",
      "channel": "maariiaacv",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Reivax2181",
      "channel": "reivax2181",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "themasterofgame0",
      "channel": "themasterofgame0",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "LalitoJoystickhands",
      "channel": "lalitojoystickhands",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "GatoTTi_10",
      "channel": "gatotti_10",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "GatoTTi_10#8195532"
    },
    {
      "name": "EmilyLaProPlayeruwu",
      "channel": "emilylaproplayeruwu",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "nannoreal",
      "channel": "nannoreal",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "ManoloMartinezGiraldo",
      "channel": "manolomartinezgiraldo",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "naachoossj",
      "channel": "naachoossj",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "budha94_",
      "channel": "budha94_",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Weedatv",
      "channel": "weedatv",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "josecor_swos",
      "channel": "josecor_swos",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Puravida20268",
      "channel": "puravida20268",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "Puravida#9124685"
    },
    {
      "name": "pastricia",
      "channel": "pastricia",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "Pastricia#5685702"
    },
    {
      "name": "Nano_eldatv",
      "channel": "nano_eldatv",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "TheNandix",
      "channel": "thenandix",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "theepunishertv",
      "channel": "theepunishertv",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "xelcharruax",
      "channel": "xelcharruax",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "JotaSniper92",
      "channel": "jotasniper92",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Kako2351",
      "channel": "kako2351",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "oscurodani",
      "channel": "oscurodani",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Cristian27_eldatv",
      "channel": "cristian27_eldatv",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "babayagalp",
      "channel": "babayagalp",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "MrlolGFX",
      "channel": "mrlolgfx",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "brossgamerx",
      "channel": "brossgamerx",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "cristian_granada",
      "channel": "cristian_granada",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "cristian_granada#8099061"
    },
    {
      "name": "spectrum2312",
      "channel": "spectrum2312",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "Spectrum23#4600832"
    },
    {
      "name": "Kolombo1988",
      "channel": "kolombo1988",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "VictorGameCube",
      "channel": "victorgamecube",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "BlascoVision",
      "channel": "blascovision",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "oOBoniOo",
      "channel": "ooBonioo",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Gabo_Conejo",
      "channel": "gabo_conejo23",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "Gabo_conejo23#5403596"
    },
    {
      "name": "Simbiotik85",
      "channel": "simbiotik85",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "SimbiotiK#3153987"
    },
    {
      "name": "Jonels05",
      "channel": "jonels05",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "Jonels#1597525"
    },
    {
      "name": "Biza_13",
      "channel": "biza_13",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "biza#3944511"
    },
    {
      "name": "Tristanchuc_",
      "channel": "tristanchuc_",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "MxniiaKo",
      "channel": "mxniiako",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "CharliUchiha",
      "channel": "charliuchiha",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Krakencosmico",
      "channel": "krakencosmico",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Nesthor96",
      "channel": "nes_thor96",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "secolomeli96",
      "channel": "secolomeli96",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Najet96",
      "channel": "xnajettw",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Bigthejoker",
      "channel": "bigthejokeryt",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Carlicox135",
      "channel": "carlicox135",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Kamikazze_Team",
      "channel": "kamikazze_team",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "Kamikazze team#1584969"
    },
    {
      "name": "Xexu",
      "channel": "xexu_watchmen",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "Xexu_watchmen#8671264"
    },
    {
      "name": "jimmy07899",
      "channel": "jimmy07899",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "pepo4",
      "channel": "pepo4",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": false,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "aspim",
      "channel": "aspim",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "greenmonkeey1",
      "channel": "greenmonkeey1",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "MonchoChavea15",
      "channel": "monchochavea15",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "MOTELWZN",
      "channel": "motelwzn",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "ggi779",
      "channel": "ggi779",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Kev_cr10",
      "channel": "kev_cr10",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "Kev_CR10#7211038"
    },
    {
      "name": "nanattosback",
      "channel": "nanattosback",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "ElYayoGamer",
      "channel": "el_yayo_gamer",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "Yayo Gamer#1531779"
    },
    {
      "name": "Yorcher2020",
      "channel": "yorcher2020",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Samuelxere",
      "channel": "samuelxere",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Majete_pk",
      "channel": "majete_pk",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "Majete_pk#3722660"
    },
    {
      "name": "twistedbull02",
      "channel": "twistedbull02",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Charliuchiha27",
      "channel": "Charliuchiha27",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Andreu_s_r97",
      "channel": "andreu_s_r97",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "ElTakuache_",
      "channel": "eltakuache_",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Kurita8",
      "channel": "kurita8",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "elcochilocotv",
      "channel": "elcochilocotv",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "pichichigamer0",
      "channel": "pichichigamer0",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": false,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "babyionya",
      "channel": "babyionya",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "JotaRomez",
      "channel": "jotaromez",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Mister_Xap",
      "channel": "mister_xap",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "jotatubala",
      "channel": "jotatubala",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Pollojeri",
      "channel": "Pollojeri",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "XxSTARxX|xdarkoff",
      "channel": "xdarkoff",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "piccoleador",
      "channel": "piccoleador",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "encuarentenaoficial",
      "channel": "encuarentenaoficial",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Paloteli",
      "channel": "paloteli",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "danihuevito5",
      "channel": "danihuevito5",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "EliaSevillano",
      "channel": "eliasevillano",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "XpomboX_",
      "channel": "xpombox_",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": false,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Marioo_Rodriguez",
      "channel": "marioo_rodriguez",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Helmin_",
      "channel": "helmin_",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "JuanCa_1811",
      "channel": "juanca_1811",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "ElRaniff",
      "channel": "elraniff",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "BetoupTV",
      "channel": "betouptv",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Skaterrios",
      "channel": "skaterrios",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "NoeJuegos",
      "channel": "noejuegos",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "victikogonzalez",
      "channel": "victikogonzalez",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "m11medina",
      "channel": "m11medina",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "morferuss",
      "channel": "morferuss",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "jimmy07899",
      "channel": "jimmy07899",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "3892_jos",
      "channel": "3892_jos",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "AMartinex",
      "channel": "AMartinex",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "byisaac1",
      "channel": "byisaac1",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Cristiangamer229",
      "channel": "cristiangamer229",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Sebv97",
      "channel": "sebv97",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "CarlosCardenash",
      "channel": "carloscardenash",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "hitman_35226",
      "channel": "hitman_35226",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Stylee_",
      "channel": "stylee_",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Sekerflay",
      "channel": "sekerflay",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "CrazyFlexxYT",
      "channel": "crazyflexxyt",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Pneonfire",
      "channel": "Pneonfire",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "twitchPneonfire#3839139"
    },
    {
      "name": "vcm97",
      "channel": "vcm97",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Morbear",
      "channel": "morbear_",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "NoWey2595",
      "channel": "nowey2595",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Globaiter",
      "channel": "globaiter",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "DeividDAVE",
      "channel": "deividdave",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "BudiGamerGirl",
      "channel": "budigamergirl",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "ByAlann",
      "channel": "ByAlann",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "La Crispa89",
      "channel": "La_crispa89",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": "La_Crispa89#6206283"
    },
    {
      "name": "xxylogicxx",
      "channel": "xxylogicxx",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": "xXYLOGYCXx#7070037"
    },
    {
      "name": "manuhe1994",
      "channel": "manuhe1994",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Botafuumeir0",
      "channel": "botafuumeir0",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "LotusBlack",
      "channel": "emperorinriver",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "FakeYuuki",
      "channel": "fakeyuukiuwu",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "CorsarioGBK",
      "channel": "corsariogbk",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Sheygam3r",
      "channel": "sheyprz",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "DocKilleer",
      "channel": "dockilleer",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "theforantu",
      "channel": "theforantu",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "KillerCuba",
      "channel": "killer_cuba",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Jerezano",
      "channel": "joaquinargudo",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Pam_TV",
      "channel": "pam_tv",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "ElFran559",
      "channel": "elfran559",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "xt_Crys_tx",
      "channel": "xt_crys_tx",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Alvarito008_",
      "channel": "alvarito008_",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "xxreblaxx07",
      "channel": "xxreblaxx07",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "D3AH00N",
      "channel": "themoon1208",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "daanilpgc",
      "channel": "daanilpgc",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "KatsuoSuke",
      "channel": "katsuosuke",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "CodilloWhite",
      "channel": "codillowhite",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "d4rkf4c3_",
      "channel": "d4rkf4c3_",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "el_papitoescanor",
      "channel": "el_papitoescanor",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "jorgee225",
      "channel": "jorgee225",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "efexexe",
      "channel": "efexexe",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "fesa88",
      "channel": "fesa88",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": false,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "cantimplora",
      "channel": "cantimplora",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "zandresx15",
      "channel": "zandresx15",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "marcossye",
      "channel": "marcossye",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "martin_xviii",
      "channel": "martin_xviii",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "BetoPalmeros",
      "channel": "betopalmeros",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "LueZz_",
      "channel": "luezz_",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "carlossanjm",
      "channel": "carlossanjm",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "lato_rang",
      "channel": "lato_rang",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "elmarto41",
      "channel": "elmarto41",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "LorenaAnerol",
      "channel": "mama_lore",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "bulldower",
      "channel": "bulldower",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Sakinuni",
      "channel": "sakinuni",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "pacorc",
      "channel": "pacorc_",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "eabigon",
      "channel": "eabigon",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "alejandrotejela",
      "channel": "alejandrotejela",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "xocas85",
      "channel": "xocas85",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "alacobo",
      "channel": "alacobo",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "drag_red80",
      "channel": "drag_red80",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "lamuerte",
      "channel": "lamuerte_20048",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Jcalzon10",
      "channel": "jcalzon10",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": false,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Andrew Rodriguewuy",
      "channel": "andrewrodriguewuy",
      "group": "6",
      "raid": "0",
      "admin": "0",
      "showstream": false,
      "broadcast_type": "",
      "plataforma": "ps4",
      "id-activision": "Andrewrodriguew#3981546"
    },
    {
      "name": "Preison",
      "channel": "prason7",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": false,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": "preison7#2509"
    },
    {
      "name": "LucarioGang",
      "channel": "lucariogang",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": false,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "TheEagleShot",
      "channel": "theeagleshot",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "ImBlueFTW",
      "channel": "imblueftw",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "MaxMax22",
      "channel": "maxmax22",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "DRbartoli",
      "channel": "drbartoli",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    },
    {
      "name": "Luismi_86",
      "channel": "luismi_86",
      "group": "2",
      "raid": "0",
      "admin": "0",
      "showstream": true,
      "broadcast_type": "affiliate",
      "plataforma": "ps4",
      "id-activision": ""
    }
  ]
